name: CI Pipeline3

on:
  workflow_dispatch:

jobs:
  test_and_lint:
    name: Test and Lint the Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        id: npm-ci
        run: npm ci

      - name: Run Lint
        id: npm-lint
        run: npm run lint

      - name: Run Tests
        id: npm-ci-test
        run: npm test

  build-and-push:
    name: Build and push docker image
    runs-on: ubuntu-latest
    needs: test_and_lint

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Login to Dockerhub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      - name: Build docker image
        run: docker buildx build -t ${{ secrets.DOCKER_USERNAME }}/github-action-school .

      - name: Push to Dockerhub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/github-action-school
